### ISSUE TITLE
Team 106 - The Kingsnakes review

### ISSUE THREAD

**Issue by chelmerrox** [ignatius22/react-calculator#4]
Hey Ignatius! 😃 Great job so far on your project and congrats on getting your milestone approved.✔

Review:
- Nice and clean UI.
- great presentation today; shows that you've understood things required of you and also on applying your knowledge correctly.
- You've got your functionality left to be done and that's probably for your next milestone. All the best with this!

**Comment by ignatius22** [comment]
thank team
